BOT_ENDPOINT = "https://botws.generals.io/"
BOT_EVENT_IDLE_TIMEOUT_SECONDS = 120
TRAINING_PROCESS_TIMEOUT_SECONDS = 2700

BOT_KEY = "sd09fjd203i0ejwi_changeme"
USER_ID = "till_bot_123"
USERNAME = "TillBot2"
TRAINING_USERNAME_PREFIX = "G2"
ROOM_ID = "TillTestRoom123"
TRAINING_SPECTATOR_ROOM_ID = "TillBotSpectatorTraining"

TILE_MOUNTAIN = -2
TILE_FOG = -3
TILE_FOG_OBSTACLE = -4

EXPAND_AFTER_TURN = 10
INTERNAL_TURNS_PER_VISIBLE_TURN = 2
SPAWN_TARGET_AFTER_TURN = 80
EDGE_TARGET_AFTER_TURN = 80

CITY_ATTACK_BUFFER = 5
MIN_CITY_ATTACK_ARMY = 45
OWN_CITY_ARMY_RESERVE = 5
OWN_CITY_PUSH_ARMY = 12
GENERAL_SEARCH_FRONTIER_BONUS_DISTANCE = 8
RESCOUT_AFTER_VISIBLE_TURNS = 40
GENERAL_SEARCH_RADIUS = 5

CENTER_REACHED_DISTANCE = 3
TILE_CATCHUP_FACTOR = 0.9

GENERAL_MIN_ARMY_RESERVE = 30
GENERAL_DEFENSE_RADIUS = 6
HIGH_ENEMY_ARMY = 20
DOMINANCE_ARMY_RATIO = 2.0
DOMINANCE_CITY_PUSH_BONUS = 18000
DOMINANCE_ROUTE_PUSH_BONUS = 9000
KNOWN_GENERAL_ROUTE_BONUS = 200000
KNOWN_GENERAL_TARGET_BONUS = 500000
ROUTE_PROGRESS_BONUS = 14000
FALLBACK_ROUTE_PROGRESS_BONUS = 9000
ROUTE_GATEWAY_BONUS = 22000
ROUTE_DISTANCE_PENALTY = 90
ENEMY_MOVEMENT_MEMORY = 60
ENEMY_PREDICTION_STEPS = 3
ENEMY_PREDICTION_MIN_HEAT = 2
TARGET_COMMITMENT_REACHED_DISTANCE = 1
TARGET_COMMITMENT_MAX_VISIBLE_TURNS = 35

AGGRESSION_PULSE_INTERVAL = 6
AGGRESSION_MIN_CHAIN_ARMY = 8
NORMAL_TILE_ARMY_SOFT_CAP = 10
NORMAL_TILE_ARMY_SOFT_CAP_START_TURN = 150
NORMAL_TILE_ARMY_SOFT_CAP_STEP_TURNS = 50
NORMAL_TILE_ARMY_SOFT_CAP_MAX = 20
FLOW_CHAIN_MEMORY = 8
FLOW_CHAIN_MIN_ARMY = 3
LOOP_DETECTION_MEMORY = 14
LOOP_TARGET_VISIT_LIMIT = 2

RESERVE_TURN_MIN = 50
RESERVE_TURN_MAX = 500
CITY_FOCUS_TURN_MIN = 60
CITY_FOCUS_TURN_MAX = 180
GENERAL_ATTACK_TURN_MIN = 100
GENERAL_ATTACK_TURN_MAX = 220
STATS_FILE = "bot_stats.json"
GENERAL_GUESS_STATS_FILE = "general_guess_stats.json"
